# vim:ft=ansible:
#
# Builds and deploys a website to a remote repository.
# The current HEAD is deployed via `git push`.
#
# Run from the git root directory
# Run with:
#   ansible-playbook -i localhost, ansible/deploy.yml
#   ansible-playbook -i localhost, ansible/deploy.yml -e "remote_name=production"
#
#
---
- hosts: 127.0.0.1
  connection: local
  force_handlers: True
  vars:
    theme_name: modpizza
  roles:
    - deploy
